config/routes.rb
Rails.application.routes.draw do
  root 'users#show'

  #refactor to namespace
  get '/signup' => 'users#new'
  get '/signup/rider' => 'users#rider_signup'
  get '/signup/driver' => 'users#driver_signup'
  resources :users, only: [:create]

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :rides, only: [:new, :create, :update, :show]
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  has_many :user_rides
  has_many :users, through: :user_rides

  enum status: ["active", "accepted", "in transit", "completed"]
  validates :pickup_address, presence: true
  validates :dropoff_address, presence: true
  validates :num_passengers, presence: true, numericality: true

  scope :active_requests, -> { where(status: "active") }
  scope :completed_rides, -> { where(status:3) }

  def format_time(time)
    time.strftime('%B %d, %Y %l:%M %p')
  end

  def rider
    users.where(role: 0).first
  end

  def driver
    users.where(role: 1).first
  end

  def has_driver?
    self.driver
  end

  def status_change_button
    case self.status
      when "active"
        "Accept"
      when "accepted"
        "Pick up Rider"
      when "in transit"
        "Complete Ride"
    end
  end

  def calculate_cost
    multiplier = (self.dropoff_time - self.pickup_time)/180
    (multiplier * 2).round(2)
  end

  def send_most_recent_time
    case self.status
      when "active"
        format_time(self.created_at)
      when "accepted"
        format_time(self.accepted_time)
      when "in transit"
        format_time(self.pickup_time)
      when "completed"
        format_time(self.dropoff_time)
    end
  end

  def update_ride_info
    directions = GoogleDirections.new(self.pickup_address, self.dropoff_address)
    update_attributes(distance: directions.distance_in_miles,
                      duration: directions.drive_time_in_minutes)
  end
end

app/models/ride_manager.rb
class RideManager
  def initialize(ride, driver)
    @ride = ride
    @current_status = ride.status
    @driver = driver
  end

  def update_ride
    if @current_status == "active"
      @driver.rides << @ride
      @ride.update_attributes(status: "accepted", accepted_time: Time.now, driver_id: @driver.id)
    elsif @current_status == "accepted"
      @ride.update_attributes(status: "in transit", pickup_time: Time.now)
    elsif @current_status == "in transit"
      @ride.update_attributes(status: "completed", dropoff_time: Time.now)
      @ride.update_attributes(cost: @ride.calculate_cost)
    else
      false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :user_rides
  has_many :rides, through: :user_rides

  enum role: %w(rider driver)

  validates :name,            presence: true
  validates :email,           presence: true,
                              uniqueness: true,
                              format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :phone_number,    presence: true,
                              uniqueness: true,
                              numericality: true,
                              length: { minimum: 10, maximum: 10 }
  validates :password_digest, presence: true

  validates_presence_of :car_make, if: ->(user) { user.role == 'driver' }
  validates_presence_of :car_model, if: ->(user) { user.role == 'driver' }
  validates_presence_of :car_capacity, if: ->(user) { user.role == 'driver' }

  def rider?
    self.role == "rider"
  end

  def driver?
    self.role == "driver"
  end

  #shared rider/driver methods
  def current_ride
    self.rides.where(status: [0,1,2]).first
  end

  #rider methods
  def has_active_rides?
    !self.current_ride.nil?
  end

  #driver methods
  def has_available_requests?
    !self.available_requests.empty?
  end

  def available_requests
    Ride.active_requests.where(num_passengers: (1..self.car_capacity).to_a)
  end
end

app/models/user_ride.rb
class UserRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/signup' unless current_user
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  before_filter :authorize
  def new
    @ride = Ride.new
  end

  def create
    ride = Ride.new(ride_params)
    if !current_user.has_active_rides?
      current_user.rides << ride
      ride.update_ride_info
      redirect_to "/"
    else
      flash[:errors] = ride.errors.full_messages.join(",")
      redirect_to(:back)
    end
  end

  def update
    ride = Ride.find(params[:id])
    if RideManager.new(ride, current_user).update_ride
      redirect_to "/"
    else
      flash[:errors] = "That ride cannot be updated at this time."
      redirect_to(:back)
    end
  end

  def show
    ride = Ride.find(params[:id])
    render status: 200,
           json: { ride: ride.as_json, time: ride.send_most_recent_time }.as_json
  end
private

  def ride_params
    params.require(:ride).permit(:pickup_address,
                                 :dropoff_address,
                                 :num_passengers)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:errors] = "Invalid Login"
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/signup'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authorize, only: [:show]

  def new

  end

  def rider_signup

  end

  def driver_signup

  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/'
    else
      flash[:errors] = user.errors.full_messages.join(",")
      redirect_to(:back)
    end
  end

  def show

  end

private
  def user_params
    params.require(:user).permit(:name,
                                 :email,
                                 :phone_number,
                                 :password,
                                 :password_confirmation,
                                 :car_make,
                                 :car_model,
                                 :car_capacity,
                                 :role)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goober</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/nav' %>
  <div class="container">
    <%= flash[:errors] %>

    <%= yield %>
  </div>
</body>
</html>

app/views/rides/_active_ride.html.erb
<strong>Pickup:</strong> <%= ride.pickup_address %><br>
<strong>Dropoff:</strong> <%= ride.dropoff_address %><br>
<strong>Distance:</strong> <%= ride.distance %> miles<br>
<strong>Length of Trip:</strong> <%= ride.duration %> minutes<br>
<strong>Passengers:</strong> <%= ride.num_passengers %><br>
<%= react_component('RideStatus', initialRide: ride, initialTime: ride.send_most_recent_time) %>


<% if current_user.driver? %>
  <%= button_to ride.status_change_button, ride_path(ride), method: "put" %>
<% end %>

app/views/rides/_driver_info.html.erb
<% driver = ride.driver %>

Driver: <%= driver.name %><br>
Car Make: <%= driver.car_make %><br>
Car Model: <%= driver.car_model %><br>

app/views/rides/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Request a Ride</h1>
  <%= form_for(@ride) do |f| %>
    <div class="form-group">
      <%= f.label :pickup_address %>
      <%= f.text_field :pickup_address, placeholder: "address or cross-street", class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label :dropoff_address %>
      <%= f.text_field :dropoff_address, placeholder: "address or cross-street", class: "form-control"  %>
    </div>

    <div class="form-group">
      <%= f.label "Number of passengers" %>
      <%= f.text_field :num_passengers, placeholder: "as a number", class: "form-control" %>
    </div>

    <p class= "center"><%= f.submit "Submit", class:"tiny button radius" %></p>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">
        <%= link_to image_tag("goober.png"), root_path, class: "logo" %> Goober
      </a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to 'Logout', '/logout' %></li>
      <% else %>
        <li><%= link_to 'Login', '/login' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/users/_completed_rides.html.erb
<table class="table table-bordered">
  <tr>
    <th>Rider</th>
    <th>Driver</th>
    <th>Pickup Address</th>
    <th>Dropoff Address</th>
    <th>Requested</th>
    <th>Accepted</th>
    <th>Picked Up</th>
    <th>Dropped Off</th>
    <th>Cost</th>
  </tr>
  <% current_user.rides.completed_rides.each do |ride| %>
    <tr>
      <td><%= ride.rider.name %></td>
      <td><%= ride.driver.name %></td>
      <td><%= ride.pickup_address %></td>
      <td><%= ride.dropoff_address %></td>
      <td><%= ride.created_at %></td>
      <td><%= ride.accepted_time %></td>
      <td><%= ride.pickup_time %></td>
      <td><%= ride.dropoff_time %></td>
      <td><%= number_to_currency ride.cost %></td>
    </tr>
  <% end %>
</table>

app/views/users/_driver_dashboard.html.erb
<h1>Driver Dashboard</h1>

<% if current_user.current_ride %>
  <div class="active-ride">
    <h2>Current Ride</h2>
    <%= render partial: 'rides/active_ride', locals: {ride: current_user.current_ride} %>
  </div>
<% elsif current_user.has_available_requests? %>
  <h2>Active Ride Requests</h2>
  <% current_user.available_requests.each do |ride| %>
    <%= render partial: 'rides/active_ride', locals: {ride: ride} %>
  <% end %>
<% end %>

app/views/users/_rider_dashboard.html.erb
<div class="col-md-6 col-md-offset-3">
  <h1>Rider Dashboard</h1>

  <% if current_user.has_active_rides? %>
    <div class="active-ride">
      <h2>Current Ride Request</h2>
      <%= render partial: 'rides/active_ride', locals: {ride: current_user.current_ride} %>
    </div>
    <% if current_user.current_ride.has_driver? %>
      <%= render partial: 'rides/driver_info', locals: {ride: current_user.current_ride} %>
    <% end %>
  <% else %>
    <div class="centered">
      <%= button_to "Request a Ride", new_ride_path, method: "get", class: "btn btn-lg btn-success" %>
    </div>
  <% end %>
</div>

app/views/users/driver_signup.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Driver Signup</h1>
  <%= form_for(User.new) do |f| %>

    <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name,  :placeholder => "name", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email,  :placeholder => "email", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number,  :placeholder => "phone", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password,  :placeholder => "password", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation,  :placeholder => "confirm password", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :car_make %>
    <%= f.text_field :car_make,  :placeholder => "car make", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :car_model %>
    <%= f.text_field :car_model,  :placeholder => "car model", class: "form-control"%>
    </div>

    <div class="form-group">
    <%= f.label :car_capacity %>
    <%= f.text_field :car_capacity,  :placeholder => "car capacity(as a number)", class: "form-control"%>
    </div>

    <%= f.hidden_field :role, value: "driver" %>
    <p class= "center"><%= f.submit "Register", class:"btn btn-md btn-success" %></p>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="col-md-2 col-md-offset-5">
  <h1>Signup</h1>
  <div class="centered">
    <%= button_to "Rider", signup_rider_path, method: "get", class: "btn btn-lg btn-success" %><br>
    <%= button_to "Driver", signup_driver_path, method: "get", class: "btn btn-lg btn-info" %>
  </div>
</div>

app/views/users/rider_signup.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>Rider Signup</h1>
  <%= form_for(User.new) do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name,  :placeholder => "name", class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email,  :placeholder => "email", class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number,  :placeholder => "phone", class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password,  :placeholder => "password", class: "form-control"%>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation,  :placeholder => "confirm password", class: "form-control"%>
    </div>

    <p class= "center"><%= f.submit "Register", class:"btn btn-md btn-success" %></p>
  <% end %>
</div>

app/views/users/show.html.erb
Welcome, <%= current_user.name %>
<br>
<% if current_user.rider? %>
  <%= render 'users/rider_dashboard' %>
<% else %>
  <%= render 'users/driver_dashboard' %>
<% end %>
<br><br>
<% unless current_user.rides.completed_rides.empty? %>
  <div id="completed-rides" class="col-lg-8 col-lg-offset-2">
    <%= render 'users/completed_rides' %>
  </div>
<% end %>